import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {ArrowRight,BrainCircuit,CheckCircle2,ChevronRight,CircleDot,Gauge,Menu,Sparkles,X} from 'lucide-react';

const STAGES=['New','Drafted','Contacted','Replied','Won','Not a fit'];
const LABELS={New:'Discovered',Drafted:'Prepared',Contacted:'Conversation',Replied:'Opportunity',Won:'Project','Not a fit':'Closed'};
const CREW=[['Scout','Discovery'],['Auditor','Measured web evidence'],['Builder','Website fit + blueprint'],['Scribe','Grounded outreach'],['Closer','Human approval'],['Brag','Launch kit']];

function ShellNav(){
 const [open,setOpen]=useState(false),reduce=useReducedMotion();
 const links=[['Overview','overview'],['Intelligence','intelligence'],['Pipeline','leads'],['Crew','crew'],['Projects','projects']];
 return <><div className="rm-command-nav"><a href="/" className="rm-wordmark"><img src="/static/logo-inverse.svg" alt="Reachmark"/></a><div className="rm-nav-links">{links.map(function(x){return <button key={x[1]} onClick={()=>x[1]==='intelligence'?document.getElementById('rm-modern-root')?.scrollIntoView({behavior:reduce?'auto':'smooth'}):window.navigate&&window.navigate(x[1])}>{x[0]}</button>})}</div><button className="rm-mobile-menu" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(true)}><Menu size={20}/></button></div>
 <AnimatePresence>{open&&<motion.div className="rm-drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setOpen(false)}><motion.aside className="rm-drawer" initial={reduce?false:{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',stiffness:420,damping:34}} onClick={e=>e.stopPropagation()}><div className="rm-drawer-head"><strong>Reachmark</strong><button onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={20}/></button></div>{links.map(function(x){return <button className="rm-drawer-link" key={x[1]} onClick={()=>{setOpen(false);if(x[1]==='intelligence')document.getElementById('rm-modern-root')?.scrollIntoView({behavior:reduce?'auto':'smooth'});else window.navigate&&window.navigate(x[1])}}>{x[0]}<ChevronRight size={17}/></button>})}</motion.aside></motion.div></AnimatePresence>}</>;
}

function Pipeline({leads}){
 const counts=useMemo(function(){return Object.fromEntries(STAGES.map(function(s){return [s,leads.filter(function(l){return l.stage===s}).length]}))},[leads]);
 return <section className="rm-panel rm-pipeline"><div className="rm-panel-head"><div><span className="rm-kicker">LIVE PIPELINE</span><h2>Move evidence into action</h2><p>Counts are read from current workspace records.</p></div><button onClick={()=>window.navigate&&window.navigate('leads')}>Open leads <ArrowRight size={16}/></button></div><div className="rm-pipeline-track">{STAGES.map(function(s,i){return <motion.div key={s} className="rm-stage" whileHover={{y:-4}} layout><div className="rm-stage-top"><span>{String(i+1).padStart(2,'0')}</span><b>{LABELS[s]}</b></div><strong>{counts[s]}</strong><small>{s}</small><div className="rm-stage-bar"><motion.i initial={{scaleX:0}} animate={{scaleX:counts[s]?1:0}} transition={{duration:.55,delay:i*.04}}/></div></motion.div>})}</div></section>;
}

function LeadIntelligence({lead,onRefresh}){
 const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(function(){let live=true;setData(null);fetch('/api/intelligence/lead/'+encodeURIComponent(lead.id),{credentials:'same-origin'}).then(function(r){return r.ok?r.json():r.json().then(function(e){throw new Error(e.error||'Unable to load intelligence')})}).then(function(v){if(live)setData(v)}).catch(function(e){if(live)setError(e.message)});return function(){live=false}},[lead.id]);
 async function audit(){setBusy(true);setError('');try{const r=await fetch('/api/leads/'+encodeURIComponent(lead.id)+'/audit',{method:'POST',headers:{'X-CSRFToken':document.querySelector('meta[name="csrf-token"]')?.content||''},credentials:'same-origin'});if(!r.ok)throw new Error('Website observation failed');await r.json();if(onRefresh)await onRefresh();}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(error)return <aside className="rm-intel-card rm-error">{error}</aside>;
 if(!data)return <aside className="rm-intel-card rm-loading"><Sparkles size={18}/> Reading workspace evidence…</aside>;
 return <motion.aside className="rm-intel-card" layout><div className="rm-intel-head"><div><span className="rm-kicker">WEBSITE FIT ENGINE</span><h3>{data.lead.name}</h3><p>{data.lead.category||'Business'} · {data.lead.city||'Location not recorded'}</p></div><span className="rm-status"><CircleDot size={12}/>{data.observation.status}</span></div><div className="rm-fit"><div><small>Direction</small><strong>{data.fit.direction}</strong></div><div><small>Conversion goal</small><strong>{data.fit.goal}</strong></div><div><small>Mobile priority</small><strong>{data.fit.mobile_priority}</strong></div></div><div className="rm-pages">{data.fit.pages.map(function(p){return <span key={p}>{p}</span>})}</div><div className="rm-evidence"><div><Gauge size={17}/><span>{data.observation.score==null?'Not scored':'Measured gap score '+data.observation.score}</span></div><span>{data.fit.evidence_state}</span></div>{data.recommendations.length>0&&<ul>{data.recommendations.slice(0,4).map(function(r){return <li key={r}><CheckCircle2 size={15}/>{r}</li>})}</ul>}<div className="rm-intel-actions"><button onClick={audit} disabled={busy}>{busy?'Checking…':'Run live observation'}</button><button onClick={()=>window.navigate&&window.navigate('portfolio')}>View concepts <ArrowRight size={15}/></button></div></motion.aside>;
}

function App(){
 const [state,setState]=useState(null),[selected,setSelected]=useState(null);
 async function load(){const r=await fetch('/api/state',{credentials:'same-origin'});if(r.ok)setState(await r.json())}
 useEffect(function(){load()},[]);
 const leads=state?.leads||[];
 useEffect(function(){if(!selected&&leads[0])setSelected(leads[0])},[leads,selected]);
 return <div className="rm-modern-shell"><ShellNav/><main className="rm-modern-main"><section className="rm-hero"><div><span className="rm-kicker">REACHMARK INTELLIGENCE</span><h1>From lead discovery to <em>build-ready direction.</em></h1><p>One evidence trail for finding the business, observing its website, choosing a fit, and moving the opportunity forward.</p><div className="rm-crew-row">{CREW.map(function(x,i){return <motion.span key={x[0]} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:i*.06}}><i>{x[0][0]}</i>{x[0]}<small>{x[1]}</small></motion.span>})}</div></div><div className="rm-orb"><motion.div animate={{rotate:360}} transition={{duration:24,repeat:Infinity,ease:'linear'}}/><BrainCircuit size={58}/><span>LIVE<br/>EVIDENCE</span></div></section>{leads.length>0?<><Pipeline leads={leads}/><section className="rm-intel-grid"><div className="rm-panel rm-leads"><div className="rm-panel-head"><div><span className="rm-kicker">OPPORTUNITY RADAR</span><h2>Choose a lead to analyze</h2></div><button onClick={()=>window.navigate&&window.navigate('leads')}>All leads <ArrowRight size={16}/></button></div><div className="rm-lead-strip">{leads.slice(0,8).map(function(l){return <button key={l.id} className={selected?.id===l.id?'selected':''} onClick={()=>setSelected(l)}><strong>{l.name}</strong><small>{l.category||'Business'} · {l.stage||'New'}</small></button>})}</div></div>{selected&&<LeadIntelligence key={selected.id} lead={selected} onRefresh={load}/>}</section></>:<section className="rm-empty"><Sparkles size={24}/><h2>Intelligence starts with real leads</h2><p>Run discovery or import a business. The workspace will then analyze measured evidence and build a website-fit direction without inventing facts.</p><button onClick={()=>window.navigate&&window.navigate('global')}>Find businesses <ArrowRight size={16}/></button></section>}</main></div>;
}
const mount=document.getElementById('rm-modern-root');if(mount)createRoot(mount).render(<App/>);
