import React, {useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence,useReducedMotion,animate} from 'framer-motion';
import {Globe2,HeartPulse,Mail,Users,ChartNoAxesCombined,Settings2,ChevronDown,Grid2X2,ArrowUpRight,LayoutDashboard,Compass,NotebookPen} from 'lucide-react';
const items=[['global',Globe2,'Global finder','Multi-location discovery jobs'],['health',HeartPulse,'Website health','Live URL checks and evidence'],['leads',Users,'Lead directory','Contacts, source details & CSV'],['outreach',Mail,'Outreach studio','Reviewed proposals & previews'],['overview',ChartNoAxesCombined,'Live dashboard','Saved activity, not estimated metrics'],['settings',Settings2,'Sender & delivery','Your profile and SMTP connection']];
function Menu(){const [open,setOpen]=useState(false);const root=useRef(null);const reduce=useReducedMotion();useEffect(()=>{function outside(e){if(!root.current?.contains(e.target))setOpen(false)}function key(e){if(e.key==='Escape')setOpen(false)}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key)}},[]);function nav(page){setOpen(false);window.navigate(page);if(!reduce)animate(document.querySelector('#page-'+page),{opacity:[0,1],y:[12,0]},{duration:.35,ease:[.16,1,.3,1]});}
return <div ref={root}><motion.button className="feature-trigger" aria-expanded={open} aria-controls="feature-dropdown" aria-label="Open features menu" whileTap={reduce?{}:{scale:.97}} onClick={()=>setOpen(!open)}><Grid2X2 size={14}/> Tools <motion.span animate={{rotate:open?180:0}}><ChevronDown size={12}/></motion.span></motion.button><AnimatePresence>{open&&<motion.div id="feature-dropdown" className="feature-dropdown" initial={reduce?false:{opacity:0,y:-8,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-6,scale:.98}} transition={{duration:.18}}><p>EVERYTHING YOU NEED TO MAKE YOUR MARK</p>{items.map(([page,Icon,title,description],i)=><motion.button key={page} className="feature-item" initial={reduce?false:{opacity:0,x:8}} animate={{opacity:1,x:0}} transition={{delay:reduce?0:i*.025}} onClick={()=>nav(page)}><Icon size={19} strokeWidth={1.6}/><span><strong>{title}</strong><small>{description}</small></span></motion.button>)}<a className="feature-item" href="/about" target="_blank" rel="noopener"><ArrowUpRight size={19}/><span><strong>About Reachmark</strong><small>How our live sources work</small></span></a><div className="menu-note">Real sources. Considered outreach. Your next move.</div></motion.div>}</AnimatePresence></div>}
createRoot(document.getElementById('feature-menu')).render(<Menu/>);
// Replace dashboard placeholders with consistent vector symbols.
const statIcons=[Users,Globe2,Mail,ChartNoAxesCombined];document.querySelectorAll('.stat-top>span').forEach((node,i)=>{const Icon=statIcons[i];if(Icon)createRoot(node).render(<Icon size={17} strokeWidth={1.5}/>)});

const navIcons={overview:LayoutDashboard,global:Compass,leads:Users,health:HeartPulse,outreach:NotebookPen,settings:Settings2};
document.querySelectorAll('.nav[data-page]').forEach(button=>{const Icon=navIcons[button.dataset.page];const node=button.querySelector('span');if(node&&Icon)createRoot(node).render(<Icon size={17} strokeWidth={1.6}/>);button.addEventListener('click',()=>{if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const page=document.querySelector('#page-'+button.dataset.page);animate(page,{opacity:[0,1],y:[9,0]},{duration:.3,ease:[.16,1,.3,1]});}});});
