"""Explicitly fictional design samples — premium Figma-inspired, never inserted into lead database."""
SAMPLES = [
    {'slug':'ember-coffee','name':'Ember & Oak','category':'Café & hospitality','style':'Warm / editorial','figma':'Figma Community · Editorial','description':'A welcoming café concept with an easy-to-browse menu and a story worth slowing down for.','image':'coffee.jpg','theme':'coffee','eyebrow':'A SMALL PAUSE. A VERY GOOD CUP.','headline':'Good mornings,\nmade slowly.','intro':'A neighbourhood coffee house concept for the moments between the rush. Thoughtful coffee, something freshly baked, and a little room to breathe.','brandmark':'e&o','services':[('Coffee, considered.','A space to introduce the coffees you serve, how you prepare them, and what makes your approach different.'),('From the oven.','A clear, easy-to-update menu for pastries, light bites, and seasonal favourites.'),('A place to stay.','Room to show your real café, share accurate opening hours, and help guests plan a visit.')],'cta':'Bring this feeling to your business.'},
    {'slug':'stillwell-studio','name':'Stillwell','category':'Wellness & beauty','style':'Calm / organic','figma':'Figma Community · Minimal','description':'An airy wellness studio concept that makes services feel clear, considered, and easy to explore.','image':'wellness.jpg','theme':'wellness','eyebrow':'A LITTLE SPACE FOR YOURSELF','headline':'Come back\nto a slower pace.','intro':'A wellness website concept built around calm spaces, thoughtful details, and a simpler path to finding the right service.','brandmark':'s.','services':[('Your treatments.','An elegant overview of your actual services, with clear descriptions and pricing once supplied.'),('Your approach.','A thoughtful introduction to the team and the principles behind the business, without invented qualifications.'),('Your next visit.','A clear enquiry path, with booking integration scoped to the system your business actually uses.')],'cta':'A considered website for a considered business.'},
    {'slug':'forma-homes','name':'Forma House','category':'Renovation & trades','style':'Architectural / confident','figma':'Figma Community · Grid','description':'A structured renovation concept with strong project imagery, clear services, and a direct estimate enquiry.','image':'home.jpg','theme':'homes','eyebrow':'GOOD SPACES START WITH GOOD QUESTIONS','headline':'Room for\nsomething better.','intro':'An architectural website concept for the people who turn ideas into places. A clear way to introduce your work and start a project conversation.','brandmark':'F/','services':[('Your projects.','A framework for your real before-and-after work, project details, and photography supplied with permission.'),('Your process.','Explain the stages from an initial conversation through a considered scope and an agreed build.'),('Your expertise.','Present the renovation services and credentials you can genuinely deliver, with no fabricated claims.')],'cta':'Give your work a better place to live.'},
    {'slug':'astra-clinic','name':'Astra Clinic','category':'Healthcare & clinic','style':'Clean / clinical','figma':'Figma Community · Health','description':'A calm, trustworthy clinic concept — clear services, practitioner profiles, and a frictionless appointment path rooted in Figma auto-layout.','image':'astra.jpg','theme':'clinic','eyebrow':'CARE, MADE CLEAR','headline':'Clarity\nfor every patient.','intro':'A premium clinic website concept that turns medical complexity into calm clarity. Trustworthy typography, soft clinical palette, and an appointment flow built for real patients.','brandmark':'A⊕','services':[('Your care.','Present your actual treatments and specialities with plain-language explanations and verified credentials.'),('Your practitioners.','Introduce the real clinicians behind the practice — photos, roles and approach, without invented claims.'),('Your appointments.','A considered booking enquiry tailored to the system your clinic actually uses, with clear next steps.')],'cta':'A clinic website patients can trust.'},
    {'slug':'novera-law','name':'Novera Law','category':'Legal & advisory','style':'Editorial / authoritative','figma':'Figma Community · Editorial Pro','description':'An authoritative law practice concept — structured case areas, team credibility, and a direct consultation enquiry inspired by Figma editorial systems.','image':'novera.jpg','theme':'law','eyebrow':'COUNSEL, WITH CLARITY','headline':'Standing\nfor what matters.','intro':'A premium legal website concept with confident editorial grids, refined serif display, and a consultation path that respects client seriousness.','brandmark':'N—','services':[('Your practice.','Structure your real case areas — from advisory to litigation — with clear scope and approach.'),('Your people.','Showcase partners and associates with actual credentials, not invented seniority.'),('Your consultation.','A direct, confidential enquiry form scoped to how your firm actually onboards clients.')],'cta':'Authority, made approachable.'},
    {'slug':'bloom-market','name':'Bloom Market','category':'Boutique & retail','style':'Vibrant / commerce','figma':'Figma Community · Commerce','description':'A vibrant boutique concept — curated product storytelling, editorial merchandising, and a seamless shopping enquiry from Figma commerce kits.','image':'bloom.jpg','theme':'bloom','eyebrow':'CURATED. CONSIDERED. YOURS.','headline':'Shop the\nstory.','intro':'A premium boutique website concept that treats products as stories. Editorial layouts, soft commerce interactions, and an enquiry-to-checkout path built for real inventory.','brandmark':'b•','services':[('Your curation.','Showcase your real products with editorial imagery and clear, accurate descriptions.'),('Your story.','Share the boutique’s point of view — sourcing, values and the people behind the selection.'),('Your checkout.','A shopping enquiry tailored to the commerce system you actually use, from simple enquiry to full checkout.')],'cta':'Commerce with editorial soul.'},
]

def find_sample(slug):
    return next((s for s in SAMPLES if s['slug']==slug), None)
