"""Explicitly fictional design samples. Never inserted into the lead database."""
SAMPLES = [
    {'slug':'ember-coffee','name':'Ember & Oak','category':'Café & hospitality','style':'Warm / editorial','description':'A welcoming café concept with an easy-to-browse menu and a story worth slowing down for.','image':'coffee.jpg','theme':'coffee','eyebrow':'A SMALL PAUSE. A VERY GOOD CUP.','headline':'Good mornings,\nmade slowly.','intro':'A neighbourhood coffee house concept for the moments between the rush. Thoughtful coffee, something freshly baked, and a little room to breathe.','brandmark':'e&o','services':[('Coffee, considered.','A space to introduce the coffees you serve, how you prepare them, and what makes your approach different.'),('From the oven.','A clear, easy-to-update menu for pastries, light bites, and seasonal favourites.'),('A place to stay.','Room to show your real café, share accurate opening hours, and help guests plan a visit.')],'cta':'Bring this feeling to your business.'},
    {'slug':'stillwell-studio','name':'Stillwell','category':'Wellness & beauty','style':'Calm / organic','description':'An airy wellness studio concept that makes services feel clear, considered, and easy to explore.','image':'wellness.jpg','theme':'wellness','eyebrow':'A LITTLE SPACE FOR YOURSELF','headline':'Come back\nto a slower pace.','intro':'A wellness website concept built around calm spaces, thoughtful details, and a simpler path to finding the right service.','brandmark':'s.','services':[('Your treatments.','An elegant overview of your actual services, with clear descriptions and pricing once supplied.'),('Your approach.','A thoughtful introduction to the team and the principles behind the business, without invented qualifications.'),('Your next visit.','A clear enquiry path, with booking integration scoped to the system your business actually uses.')],'cta':'A considered website for a considered business.'},
    {'slug':'forma-homes','name':'Forma House','category':'Renovation & trades','style':'Architectural / confident','description':'A structured renovation concept with strong project imagery, clear services, and a direct estimate enquiry.','image':'home.jpg','theme':'homes','eyebrow':'GOOD SPACES START WITH GOOD QUESTIONS','headline':'Room for\nsomething better.','intro':'An architectural website concept for the people who turn ideas into places. A clear way to introduce your work and start a project conversation.','brandmark':'F/','services':[('Your projects.','A framework for your real before-and-after work, project details, and photography supplied with permission.'),('Your process.','Explain the stages from an initial conversation through a considered scope and an agreed build.'),('Your expertise.','Present the renovation services and credentials you can genuinely deliver, with no fabricated claims.')],'cta':'Give your work a better place to live.'},
]

def find_sample(slug):
    return next((s for s in SAMPLES if s['slug']==slug), None)
